version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortner_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  cache:
    image: redis:latest
    ports:
      - 6379:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "npm install && npm run start"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - cache

volumes:
  postgres_data:
